/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c RhevCred -p RhevCred.h:RhevCred.cpp credentials.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef RHEVCRED_H_1300614447
#define RHEVCRED_H_1300614447

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.redhat.rhevm.Credentials
 */
class RhevCred: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.redhat.rhevm.Credentials"; }

public:
    RhevCred(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~RhevCred();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void UserAuthenticated(const QString &token);
};

namespace com {
  namespace redhat {
    namespace rhevm {
      typedef ::RhevCred Credentials;
    }
  }
}
#endif
