#!/bin/bash
set -e

udevadm control --reload-rules
udevadm trigger --subsystem-match="virtio-ports" --attr-match="name=com.redhat.rhevm.vdsm"
udevadm trigger --subsystem-match="virtio-ports" --attr-match="name=ovirt-guest-agent.0"
udevadm settle

#DEBHELPER#
