#!/bin/sh

usage() {
    echo "usage: $0 disk|mem"
    exit 1
}

state="$1"

if [ $state == "disk" ]; then
    param="hibernate"
elif [ $state == "mem" ]; then
    param="suspend"
else
    usage
fi

pm=`which pm-$param`

if [ -x $pm ]; then
    $pm
else
    echo $state > /sys/power/state
fi
