#!/usr/bin/python2

import platform

arch_replace = {
    'i686': 'x86',
    'i586': 'x86',
    'i386': 'x86'}


def get_arch():
    arch = platform.uname()[-2].lower().strip()
    if arch in arch_replace:
        return arch_replace[arch]
    return arch


try:
    info = platform.linux_distribution()
except AttributeError:
    info = platform.dist()
    if info[0] == 'redhat':
        try:
            f = open('/etc/redhat-release', 'r')
            r = f.read().split(' release ', 1)
            f.close()
            info = (r[0],) + info[1:]
        except IOError:
            pass

print 'distribution=%s' % info[0]
print 'version=%s' % info[1]
print 'codename=%s' % info[2]
print 'arch=%s' % get_arch()
print 'kernel=%s' % platform.release()
print 'type=linux'
