#!/usr/bin/python

import platform


try:
    info = platform.linux_distributions()
except AttributeError:
    info = platform.dist()
    if info[0] == 'redhat':
        try:
            f = open('/etc/redhat-release', 'r')
            r = f.read().split(' release ', 1)
            f.close()
            info = (r[0],) + info[1:]
        except IOError:
            pass

print 'distribution=%s' % info[0]
print 'version=%s' % info[1]
print 'codename=%s' % info[2]
print 'arch=%s' % platform.uname()[-1]
print 'kernel=%s' % platform.release()
print 'type=linux'
